import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, ShieldCheck, Wallet } from "lucide-react";
import { ShareSheet } from "@/components/share/ShareSheet";
import { CagnotteMediaViewer } from "@/components/cagnottes/CagnotteMediaViewer";
import { SUBTYPE_LABELS } from "@/lib/constants";
import { formatPrice } from "@/lib/format";
import { normalizeLegacyDescription, stripHtml } from "@/lib/sanitize";
import { cn } from "@/lib/utils";
import { ProgressPoll } from "./ProgressPoll";

const BACKEND_API_URL =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";
const PUBLIC_BASE_URL =
  process.env.NEXT_PUBLIC_BASE_URL || "https://cagnotte.sn";

// CRITICAL — OQ-3 / Pitfall P05 mitigation. Never pre-render at build time.
export const dynamic = "force-dynamic";

interface GalleryItem {
  // "youtube" preserved as legacy alias for "video"+provider="youtube".
  kind: "image" | "video" | "youtube";
  url: string;
  videoId?: string;
  provider?: "youtube" | "vimeo" | "wistia" | "loom";
}

interface CagnotteDetail {
  id: string;
  slug: string;
  title: string;
  description: string | null;
  coverUrl: string | null;
  subtype: "festive" | "solidaire" | null;
  visibility: "public" | "private";
  status: "active" | "closed";
  gallery: GalleryItem[];
  goalAmount: number | null;
  endDate: string | null;
  hideAmount: boolean;
  hideDonors: boolean;
  totalRaised: number | null;
  donorCount: number | null;
  recentDonations: Array<{
    id: string;
    amount: number | null;
    name: string | null;
    message: string | null;
    createdAt: string;
  }>;
  seller: {
    id: string;
    slug: string;
    displayName: string;
    avatarUrl: string | null;
  } | null;
  createdAt: string;
}

interface ParticipantItem {
  id: string;
  amount: number | null;
  name: string | null;
  message: string | null;
  createdAt: string;
}

interface ParticipantsResponse {
  participants: ParticipantItem[];
  nextCursor: string | null;
}

async function getCagnotte(slug: string): Promise<CagnotteDetail | null> {
  try {
    const res = await fetch(`${BACKEND_API_URL}/api/cagnottes/${slug}`, {
      cache: "no-store",
    });
    if (res.status === 404) return null;
    if (!res.ok) return null;
    return (await res.json()) as CagnotteDetail;
  } catch {
    return null;
  }
}

async function getParticipants(slug: string): Promise<ParticipantsResponse> {
  try {
    const res = await fetch(
      `${BACKEND_API_URL}/api/cagnottes/${slug}/participants?limit=50`,
      { cache: "no-store" },
    );
    if (!res.ok) return { participants: [], nextCursor: null };
    return (await res.json()) as ParticipantsResponse;
  } catch {
    return { participants: [], nextCursor: null };
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const cagnotte = await getCagnotte(slug);
  if (!cagnotte) {
    return {
      title: "Cagnotte introuvable",
      robots: { index: false, follow: false },
    };
  }

  // Strip tags so the meta description stays plain text (OG + SEO).
  const descriptionPlain = (
    stripHtml(cagnotte.description ?? "") || "Soutiens cette cagnotte sur cagnotte.sn"
  ).slice(0, 200);
  const description = descriptionPlain;

  // OG image is auto-generated by opengraph-image.tsx (branded card with
  // cover overlay or navy/pink fallback). Next.js injects the og:image tag
  // automatically — no manual `images` field needed.
  return {
    title: cagnotte.title,
    description: description.slice(0, 155),
    openGraph: {
      title: cagnotte.title,
      description,
      url: `${PUBLIC_BASE_URL}/c/${slug}`,
      type: "article",
      siteName: "cagnotte.sn",
      locale: "fr_FR",
    },
    twitter: {
      card: "summary_large_image",
      title: cagnotte.title,
      description,
    },
    // Public cagnottes are indexable; private ones are noindex.
    robots: cagnotte.visibility === "public"
      ? { index: true, follow: true }
      : { index: false, follow: false },
    alternates: {
      canonical: `${PUBLIC_BASE_URL}/c/${slug}`,
    },
  };
}

function formatRelative(iso: string): string {
  try {
    const now = Date.now();
    const then = new Date(iso).getTime();
    const diff = now - then;
    const mins = Math.floor(diff / 60000);
    if (mins < 1) return "à l'instant";
    if (mins < 60) return `Il y a ${mins} min`;
    const hours = Math.floor(mins / 60);
    if (hours < 24) return `Il y a ${hours}h`;
    const days = Math.floor(hours / 24);
    if (days === 1) return "Hier";
    if (days < 7) return `Il y a ${days} jours`;
    const weeks = Math.floor(days / 7);
    if (weeks < 5) return `Il y a ${weeks} sem.`;
    const months = Math.floor(days / 30);
    return `Il y a ${months} mois`;
  } catch {
    return "";
  }
}

function initial(name: string | null | undefined): string {
  if (!name) return "?";
  const trimmed = name.trim();
  return trimmed.charAt(0).toUpperCase() || "?";
}

export default async function CagnottePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const [cagnotte, participantsData] = await Promise.all([
    getCagnotte(slug),
    getParticipants(slug),
  ]);

  if (!cagnotte) notFound();

  const isPrivate = cagnotte.visibility === "private";
  const isClosed = cagnotte.status === "closed";
  // Expiration check — aligné avec le guard backend (orders.ts POST /api/orders) :
  // la date de fin est comptée comme la fin du JOUR endDate (23:59:59.999).
  // Tant qu'elle n'est pas dépassée, les dons restent acceptés.
  const isExpired = (() => {
    if (!cagnotte.endDate) return false;
    const end = new Date(cagnotte.endDate);
    if (Number.isNaN(end.getTime())) return false;
    end.setHours(23, 59, 59, 999);
    return new Date() > end;
  })();
  const isUnavailable = isClosed || isExpired;
  const subtype = (cagnotte.subtype ?? "festive") as "festive" | "solidaire";
  const goalAmount = cagnotte.goalAmount ?? 0;
  const totalRaised = cagnotte.totalRaised ?? 0;
  const donorCount = cagnotte.donorCount ?? 0;
  const sellerName = cagnotte.seller?.displayName ?? "Anonyme";

  const participants = participantsData.participants;
  // Show the 10 most recent contributions only — the API is already
  // sorted DESC by createdAt, so slice from the head. Cap is hard so
  // a cagnotte with thousands of donors stays scannable.
  const donorWall = participants.slice(0, 10);

  // Inline participants block — rendered TWICE (mobile after aside,
  // desktop in left column) via order-independent visibility classes
  // so creators see the live donor wall right under "Je participe"
  // on mobile, while desktop keeps the original two-column layout.
  const showParticipants = !cagnotte.hideDonors && donorWall.length > 0;
  const participantsSection = showParticipants ? (
    <section
      id="participants"
      className="scroll-mt-20 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/5 sm:p-8 md:p-6"
    >
      <div className="mb-6 flex items-center justify-between md:mb-8">
        <h2 className="font-headings text-xl font-black text-primary sm:text-2xl">
          Participants ({donorCount})
        </h2>
        {donorCount > donorWall.length ? (
          <span className="text-xs font-bold text-gray-500 sm:text-sm">
            10 plus récents
          </span>
        ) : null}
      </div>
      <ul className="grid grid-cols-1 gap-4 md:grid-cols-2 md:gap-6">
        {donorWall.map((p) => {
          const maskedAmount = cagnotte.hideAmount || p.amount === null;
          return (
            <li
              key={p.id}
              className="flex gap-4 rounded-2xl border border-gray-100 p-4 transition-colors hover:border-gray-200"
            >
              <div
                aria-hidden
                className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-pink-dark font-bold text-primary"
              >
                {initial(p.name)}
              </div>
              <div className="min-w-0 flex-1">
                <p className="truncate font-bold text-primary">
                  {p.name ?? "Anonyme"}
                </p>
                <p className="flex items-center gap-2 text-xs font-medium text-gray-500 sm:text-sm">
                  <span
                    className={cn(
                      maskedAmount
                        ? "italic text-gray-500"
                        : "font-bold text-primary",
                    )}
                  >
                    {maskedAmount
                      ? "Anonyme"
                      : formatPrice(p.amount as number)}
                  </span>
                  <span aria-hidden>•</span>
                  <span className="truncate">
                    {formatRelative(p.createdAt)}
                  </span>
                </p>
                {p.message ? (
                  <p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-gray-700">
                    <span aria-hidden className="mr-1">&ldquo;</span>
                    {p.message}
                    <span aria-hidden className="ml-0.5">&rdquo;</span>
                  </p>
                ) : null}
              </div>
            </li>
          );
        })}
      </ul>
    </section>
  ) : null;

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Event",
    name: cagnotte.title,
    description: stripHtml(cagnotte.description ?? "") || undefined,
    url: `${PUBLIC_BASE_URL}/c/${slug}`,
    startDate: cagnotte.createdAt,
    endDate: cagnotte.endDate || undefined,
    organizer: {
      "@type": "Person",
      name: sellerName,
    },
    eventStatus: "https://schema.org/EventScheduled",
    eventAttendanceMode: "https://schema.org/OnlineEventAttendanceMode",
    location: {
      "@type": "VirtualLocation",
      url: `${PUBLIC_BASE_URL}/c/${slug}`,
    },
    inLanguage: "fr",
  };

  return (
    <article className="bg-gray-50 pb-10 sm:pb-12 md:pb-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <div className="mx-auto max-w-6xl px-3 py-5 sm:px-4 sm:py-6 md:px-6 md:py-6 lg:px-8">
        {isPrivate ? (
          <div
            role="status"
            className="mb-4 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"
          >
            Cagnotte privée — accessible uniquement via le lien direct.
          </div>
        ) : null}

        <div className="flex flex-col items-start gap-6 lg:flex-row lg:gap-8">
          {/* ─── Left: cover + story + participants grid ───────────────── */}
          <div className="w-full space-y-6 lg:w-2/3 lg:space-y-8">
            {/* Cover + media viewer (Skool-style) + header card */}
            <section className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-black/5">
              <CagnotteMediaViewer
                coverUrl={cagnotte.coverUrl}
                title={cagnotte.title}
                gallery={cagnotte.gallery ?? []}
                subtype={subtype}
                subtypeLabel={SUBTYPE_LABELS[subtype]}
              />

              <div className="p-5 sm:p-8 md:p-6">
                <h1 className="mb-6 font-headings text-xl font-black leading-tight text-primary sm:text-2xl md:text-3xl lg:text-3xl">
                  {cagnotte.title}
                </h1>

                {/* Organisée par row */}
                <div className="mb-6 flex items-center gap-4 border-y border-gray-100 py-5 sm:py-4 md:mb-6">
                  {cagnotte.seller?.avatarUrl ? (
                    <Image
                      src={cagnotte.seller.avatarUrl}
                      alt=""
                      width={56}
                      height={56}
                      sizes="56px"
                      className="h-12 w-12 shrink-0 rounded-full object-cover sm:h-14 sm:w-14"
                    />
                  ) : (
                    <div
                      aria-hidden
                      className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-pink-dark font-headings text-lg font-black text-primary sm:h-14 sm:w-14"
                    >
                      {initial(sellerName)}
                    </div>
                  )}
                  <div className="min-w-0">
                    <p className="mb-0.5 text-xs font-medium text-gray-500 sm:text-sm">
                      Organisée par
                    </p>
                    <p className="truncate font-headings text-base font-bold text-primary sm:text-lg">
                      {sellerName}
                    </p>
                  </div>
                </div>

                {/* Description — rich-text HTML, sanitized on ingest
                    (backend) AND here at render time (defense in depth
                    per CLAUDE.md Audit 011). `prose` gives typography
                    defaults + `prose-a:*` maps links to Banani navy. */}
                {cagnotte.description ? (
                  <details className="group">
                    <summary className="cursor-pointer list-none">
                      <div
                        className="prose prose-base max-w-none text-gray-700 prose-p:my-3 prose-p:leading-relaxed prose-strong:text-primary prose-em:text-primary prose-a:text-primary prose-a:underline prose-a:underline-offset-2 line-clamp-8 group-open:line-clamp-none md:prose-lg"
                        dangerouslySetInnerHTML={{
                          __html: normalizeLegacyDescription(cagnotte.description),
                        }}
                      />
                      <span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-primary group-open:hidden">
                        Lire toute l&apos;histoire
                        <ArrowRight
                          size={16}
                          aria-hidden
                          className="transition-transform group-hover:translate-x-1"
                        />
                      </span>
                      <span className="mt-4 hidden items-center gap-2 text-sm font-bold text-primary group-open:inline-flex">
                        ← Réduire
                      </span>
                    </summary>
                  </details>
                ) : null}
              </div>
            </section>

            {/* Participants grid — DESKTOP only (≥ lg). Mobile gets a
                duplicate copy rendered AFTER the aside so creators see
                their participation card first then the donor wall. */}
            <div className="hidden lg:block">{participantsSection}</div>
          </div>

          {/* ─── Right: sticky action card + share card below ──────────── */}
          <aside className="w-full lg:w-1/3">
            <div className="lg:sticky lg:top-24 flex flex-col gap-4">
              {/* Card 1 — Participation (focus on CTA) */}
              <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-[0_8px_30px_rgb(0,0,0,0.08)] sm:p-6">
                {/* Live amount + animated progress bar + caption */}
                <ProgressPoll
                  slug={slug}
                  initialTotalRaised={totalRaised}
                  initialDonorCount={donorCount}
                  goalAmount={goalAmount}
                  hideAmount={cagnotte.hideAmount}
                  hideDonors={cagnotte.hideDonors}
                />

                {/* Je participe CTA — pink Banani variant with shine sweep */}
                {isUnavailable ? (
                  <div className="space-y-2">
                    <div
                      role="status"
                      className="flex min-h-14 w-full items-center justify-center rounded-2xl bg-gray-100 px-4 text-center text-sm font-semibold text-gray-600"
                    >
                      {isClosed
                        ? "Cagnotte clôturée — les dons ne sont plus acceptés"
                        : "Cagnotte terminée — la date de fin est dépassée"}
                    </div>
                    {isExpired && !isClosed ? (
                      <p className="text-center text-xs text-gray-500">
                        Si c'est votre cagnotte, prolongez la date de fin depuis
                        votre tableau de bord pour la réactiver.
                      </p>
                    ) : null}
                  </div>
                ) : (
                  <Link
                    href={`/c/${slug}/participer`}
                    className="group relative flex min-h-14 w-full items-center justify-center overflow-hidden rounded-2xl bg-pink-dark py-4 font-headings text-lg font-black text-primary shadow-sm transition-all duration-200 ease-out hover:-translate-y-0.5 hover:bg-pink-cta-hover hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 active:translate-y-0 active:scale-[0.98]"
                  >
                    <span
                      aria-hidden
                      className="pointer-events-none absolute inset-y-0 -left-[50%] w-[50%] animate-button-shine-sweep bg-gradient-to-r from-transparent via-white/55 to-transparent"
                    />
                    <span className="relative">Je participe</span>
                  </Link>
                )}

                {/* Trust items */}
                <div className="mt-5 space-y-4 border-t border-gray-100 pt-5">
                  <div className="flex items-start gap-3">
                    <ShieldCheck
                      size={20}
                      aria-hidden
                      className="mt-0.5 shrink-0 text-green-500"
                    />
                    <div>
                      <p className="mb-0.5 text-sm font-bold text-primary">
                        Paiement 100 % sécurisé
                      </p>
                      <p className="text-xs font-medium text-gray-500">
                        Tes données sont cryptées et protégées
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <Wallet
                      size={20}
                      aria-hidden
                      className="mt-0.5 shrink-0 text-blue-500"
                    />
                    <div>
                      <p className="mb-0.5 text-sm font-bold text-primary">
                        Fonds versés en 48 h
                      </p>
                      <p className="text-xs font-medium text-gray-500">
                        Versement sur Wave ou Orange Money — jours ouvrés.
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Card 2 — Share (separate card, below) */}
              <div className="rounded-2xl bg-pink p-5 text-center shadow-[0_8px_30px_rgb(0,0,0,0.06)] sm:p-6">
                <h3 className="mb-2 font-headings text-base font-black text-primary sm:text-lg">
                  Partager, c&apos;est aussi soutenir
                </h3>
                <p className="mb-4 text-xs font-medium text-primary/70 sm:text-sm">
                  Chaque partage offre une chance supplémentaire d&apos;atteindre
                  l&apos;objectif.
                </p>
                <ShareSheet
                  url={`${PUBLIC_BASE_URL}/c/${slug}`}
                  title={cagnotte.title}
                  description={stripHtml(cagnotte.description ?? "") || undefined}
                />
              </div>
            </div>
          </aside>

          {/* Participants — MOBILE only (< lg). Rendered AFTER the aside
              in DOM order so it sits below "Je participe / Partager"
              once the layout stacks vertically on mobile. */}
          <div className="block w-full lg:hidden">{participantsSection}</div>
        </div>
      </div>

    </article>
  );
}
