import { notFound, redirect } from "next/navigation";
import type { Metadata } from "next";
import { SellerHeader } from "@/components/store/SellerHeader";
import { IzyFooter } from "@/components/store/IzyFooter";
import { LinkBlock } from "@/components/store/blocks/LinkBlock";
import { StoreCard } from "@/components/store/blocks/StoreCard";
import { StoreThemeProvider } from "@/components/store/StoreThemeProvider";
import { PageTracker } from "@/components/store/PageTracker";
import { BlockClickTracker } from "@/components/store/BlockClickTracker";
import { ShareButton } from "@/components/store/ShareButton";
import { BlockShareButton } from "@/components/store/BlockShareButton";
import { StoreBlockLink } from "@/components/store/StoreBlockLink";
import { InlineCheckoutCard } from "@/components/store/InlineCheckoutCard";
import { OwnerDashboardButton } from "@/components/store/OwnerDashboardButton";
import { PixelScripts } from "@/components/store/PixelScripts";
import { getResolvedTheme } from "@/types";
import { formatPrice } from "@/lib/utils";
import type { SellerWithBlocks, Block, HeaderStyle } from "@/types";

export const dynamic = "force-dynamic";

const PERIOD_LABELS: Record<string, string> = {
  WEEKLY: "/ sem.",
  BIWEEKLY: "/ 15j",
  MONTHLY: "/ mois",
  QUARTERLY: "/ trim.",
  YEARLY: "/ an",
};

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://izy.store";

interface StorePageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: StorePageProps): Promise<Metadata> {
  const { slug } = await params;
  const { seller } = await getSeller(slug);

  if (!seller) {
    return { title: "Page introuvable" };
  }

  const title = `${seller.displayName} | Izy`;
  const description = seller.bio || `Découvre les produits et services de ${seller.displayName} sur Izy`;
  const url = `${BASE_URL}/${slug}`;

  // OG image is auto-generated by opengraph-image.tsx (dynamic 1200x630 with avatar + name)
  return {
    title,
    description,
    alternates: { canonical: url },
    other: { "theme-color": "#0D9488" },
    openGraph: {
      title,
      description,
      url,
      siteName: "Izy",
      locale: "fr_FR",
      type: "profile",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

async function getSeller(slug: string): Promise<{ seller: SellerWithBlocks | null; backendDown: boolean; redirectSlug?: string }> {
  try {
    const res = await fetch(`${API_URL}/api/sellers/${slug}`, {
      cache: "no-store",
    });
    if (res.status === 301) {
      const data = await res.json();
      return { seller: null, backendDown: false, redirectSlug: data.redirect };
    }
    if (res.status === 404) return { seller: null, backendDown: false };
    if (!res.ok) return { seller: null, backendDown: true };
    const data = await res.json();
    return { seller: data.seller, backendDown: false };
  } catch {
    return { seller: null, backendDown: true };
  }
}

const BASE_URL_SHARE = process.env.NEXT_PUBLIC_BASE_URL || "https://izy.store";


function getBlockSubtitle(block: Block): string | null {
  const config = (block.config as Record<string, unknown>) || {};

  switch (block.type) {
    case "SALE": {
      if (!block.product) return null;
      const p = block.product;
      const hasDiscount = p.discountPrice && p.discountPrice > 0 && p.discountPrice < p.price;
      return p.price > 0 ? formatPrice(hasDiscount ? p.discountPrice! : p.price) : "Gratuit";
    }
    case "BOOKING": {
      if (!block.bookingService) return null;
      const s = block.bookingService;
      const parts = [formatPrice(s.price)];
      if (s.duration) parts.push(`${s.duration} min`);
      return parts.join(" · ");
    }
    case "LEAD_MAGNET": {
      if (!block.product) return null;
      return block.product.price > 0 ? formatPrice(block.product.price) : "Gratuit";
    }
    case "WAITING_LIST":
      return "Liste d\u2019attente";
    case "PAYMENT":
      return "Paiement libre";
    case "DONATION":
      return "Don libre";
    case "FUNDRAISER":
      return "Levée de fonds";
    case "FORMATION": {
      if (!block.product) return null;
      const fp = block.product;
      const hasDiscount = fp.discountPrice && fp.discountPrice > 0 && fp.discountPrice < fp.price;
      return fp.price > 0 ? formatPrice(hasDiscount ? fp.discountPrice! : fp.price) : "Gratuit";
    }
    case "PARTNERSHIP":
      return "Partenariat";
    case "COMMUNITY": {
      if (!block.community) return null;
      const c = block.community;
      // Priorité : description courte du vendeur (ex. "Rejoins le club")
      // Fallback : prix + période
      if (c.description) {
        const firstLine = c.description.split("\n")[0].trim();
        return firstLine.length > 60 ? firstLine.slice(0, 57) + "…" : firstLine;
      }
      const period = PERIOD_LABELS[c.billingPeriod || "MONTHLY"] || "/ mois";
      return `${formatPrice(c.priceAmount)} ${period}`;
    }
    default:
      return null;
  }
}

function hasLandingContent(block: Block): boolean {
  const config = block.config as Record<string, unknown> | null;
  const pAny = block.product as Record<string, unknown> | null;
  const sAny = block.bookingService as unknown as Record<string, unknown> | null;

  const description = block.product?.description || block.bookingService?.description
    || block.community?.description || (config?.description as string) || "";
  const plainText = description.replace(/<[^>]*>/g, "").replace(/&nbsp;/g, " ").trim();
  if (plainText.length >= 10) return true;

  // Pour PAYMENT/DONATION, la couverture seule ne justifie pas une page détail
  // — elle est déjà visible sur la card du store
  const skipCoverOnly = block.type === "PAYMENT" || block.type === "DONATION" || block.type === "FUNDRAISER";
  if (!skipCoverOnly) {
    const coverUrl = block.product?.coverUrl || block.bookingService?.coverUrl
      || block.community?.coverUrl || (config?.coverUrl as string) || null;
    if (coverUrl) return true;
  }

  const videoUrl = (pAny?.videoUrl as string) || (sAny?.videoUrl as string) || (config?.videoUrl as string) || null;
  if (videoUrl && videoUrl.trim().startsWith("http")) return true;

  const sections = pAny?.checkoutSections || sAny?.checkoutSections || config?.checkoutSections;
  if (Array.isArray(sections) && sections.some((s: Record<string, unknown>) => {
    if (s.type === "text") return ((s.content as string) || "").replace(/<[^>]*>/g, "").trim().length >= 10;
    if (s.type === "faq") return Array.isArray(s.items) && s.items.some((i: Record<string, string>) => (i.question || "").trim().length > 0 || (i.answer || "").trim().length > 0);
    if (s.type === "features") return Array.isArray(s.items) && s.items.some((i: Record<string, string>) => (i.text || "").trim().length > 0);
    if (s.type === "video") return !!((s.content as string) || "").trim();
    return false;
  })) return true;

  if (block.product?.reviews && block.product.reviews.length > 0) return true;

  return false;
}

function BlockRenderer({ block, sellerSlug, sellerTimezone, sellerName, blockLayout }: { block: Block; sellerSlug: string; sellerTimezone: string; sellerName?: string; blockLayout?: string }) {
  const config = (block.config as Record<string, unknown>) || {};

  // ── LINK blocks keep their own component ──
  if (block.type === "LINK") {
    if (!config.url) return null;
    const linkTitle = (config.title as string) || block.title;
    const shareUrl = config.url as string;
    return (
      <BlockClickTracker slug={sellerSlug} blockId={block.id}>
        <div className="relative">
          <div className="absolute right-2 top-0 bottom-0 z-10 flex items-center">
            <BlockShareButton blockTitle={linkTitle} shareUrl={shareUrl} sellerSlug={sellerSlug} />
          </div>
          <LinkBlock
            title={linkTitle}
            url={config.url as string}
            icon={(config.icon as string) || "other"}
            coverUrl={config.coverUrl as string | undefined}
            ctaStyle={(config.ctaStyle as string) || "button"}
            blockLayout={blockLayout}
          />
        </div>
      </BlockClickTracker>
    );
  }

  // ── All other blocks → StoreCard ──
  const blockTitle =
    block.product?.title ||
    block.bookingService?.title ||
    block.community?.title ||
    (config.title as string) ||
    block.title;

  const coverUrl =
    block.product?.coverUrl ||
    block.bookingService?.coverUrl ||
    block.community?.coverUrl ||
    (config.coverUrl as string) ||
    null;

  const defaultCtaStyle = blockLayout === "card-image-top" ? "preview" : "button";
  const ctaStyle =
    block.product?.ctaStyle ||
    block.bookingService?.ctaStyle ||
    (config.ctaStyle as string) ||
    defaultCtaStyle;

  const blockDescription =
    block.product?.description ||
    block.bookingService?.description ||
    block.community?.description ||
    (config.description as string) ||
    null;

  const subtitle = getBlockSubtitle(block);
  const shareUrl = `${BASE_URL_SHARE}/${sellerSlug}/${block.id}`;

  const storeCard = (
    <StoreCard
      title={blockTitle}
      subtitle={subtitle}
      coverUrl={coverUrl}
      blockType={block.type}
      ctaStyle={ctaStyle}
      description={blockDescription}
    />
  );

  // Routing logic:
  // - SALE, BOOKING, LEAD_MAGNET, PARTNERSHIP, COMMUNITY → always detail page
  // - DONATION, PAYMENT, WAITING_LIST → detail page if has content, modal if not
  const ALWAYS_DETAIL_TYPES = ["SALE", "FORMATION", "BOOKING", "LEAD_MAGNET", "PARTNERSHIP", "COMMUNITY"];
  const goToDetailPage = ALWAYS_DETAIL_TYPES.includes(block.type) || hasLandingContent(block);

  const defaultButtonText = block.type === "COMMUNITY" ? "Rejoindre" : block.type === "FUNDRAISER" ? "Participer" : block.type === "DONATION" ? "Faire un don" : block.type === "PAYMENT" ? "Payer" : block.type === "PARTNERSHIP" ? "Proposer" : block.type === "BOOKING" ? "Réserver" : block.type === "FORMATION" ? "Accéder" : "Acheter";
  const buttonText = block.product?.buttonText || block.bookingService?.buttonText || (config.buttonText as string) || defaultButtonText;
  const price = block.product?.price || block.bookingService?.price || block.community?.priceAmount || 0;
  const discountPrice = block.product?.discountPrice || null;

  return (
    <BlockClickTracker slug={sellerSlug} blockId={block.id}>
      <div className="relative">
        <div className="absolute right-2 top-0 bottom-0 z-10 flex items-center">
          <BlockShareButton blockTitle={blockTitle} shareUrl={shareUrl} sellerSlug={sellerSlug} />
        </div>
        {goToDetailPage ? (
          <StoreBlockLink href={`/${sellerSlug}/${block.id}`}>
            {storeCard}
          </StoreBlockLink>
        ) : (
          <InlineCheckoutCard
            block={block}
            sellerSlug={sellerSlug}
            sellerTimezone={sellerTimezone}
            sellerName={sellerName}
            buttonText={buttonText}
            price={price}
            discountPrice={discountPrice}
          >
            {storeCard}
          </InlineCheckoutCard>
        )}
      </div>
    </BlockClickTracker>
  );
}

export default async function StorePage({ params }: StorePageProps) {
  const { slug } = await params;
  const { seller, backendDown, redirectSlug } = await getSeller(slug);

  if (redirectSlug) {
    redirect(`/${redirectSlug}`);
  }
  if (!seller && backendDown) {
    throw new Error("Service temporairement indisponible");
  }
  if (!seller) notFound();

  const themeConfig = {
    themeId: seller.themeId || "default",
    themeFont: seller.themeFont || "inter",
    themeColors: (seller.themeColors as { primary?: string; background?: string; button?: string } | null) || null,
  };

  const resolvedTheme = getResolvedTheme(themeConfig);

  return (
    <StoreThemeProvider themeConfig={themeConfig} bgImageUrl={seller.bgImageUrl} imageStyle={seller.imageStyle}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "ProfilePage",
            name: seller.displayName,
            description: seller.bio || `Découvre les produits et services de ${seller.displayName}`,
            url: `${BASE_URL}/${slug}`,
            ...(seller.avatarUrl && { image: seller.coverUrl || seller.avatarUrl }),
            mainEntity: {
              "@type": "Person",
              name: seller.displayName,
              url: `${BASE_URL}/${slug}`,
              ...(seller.avatarUrl && { image: seller.avatarUrl }),
              ...(seller.instagramUrl && { sameAs: [seller.instagramUrl, seller.youtubeUrl, seller.twitterUrl, seller.facebookUrl, seller.tiktokUrl, seller.websiteUrl].filter(Boolean) }),
            },
          }),
        }}
      />
      <PageTracker slug={slug} />
      <PixelScripts
        metaPixelId={seller.metaPixelId}
        googleAdsId={seller.googleAdsId}
        googleAnalyticsId={seller.googleAnalyticsId}
        tiktokPixelId={seller.tiktokPixelId}
      />
      <OwnerDashboardButton sellerSlug={seller.slug} />
      <div className="@container mx-auto min-h-screen max-w-lg px-4 pt-8 pb-10 md:pt-14 md:pb-16 relative">
        {/* Share button — top right */}
        <div className="absolute top-8 right-4 md:top-14 md:right-0 z-20">
          <ShareButton slug={slug} displayName={seller.displayName} />
        </div>

        {/* Suspect badge — shown if admin flagged this profile */}
        {seller.isFlagged && (
          <div className="mb-4 flex items-center gap-2 rounded-xl border px-3 py-2.5"
            style={{
              backgroundColor: "var(--theme-card-bg, rgba(239,68,68,0.08))",
              borderColor: "var(--theme-card-border, rgba(239,68,68,0.15))",
            }}
          >
            <svg viewBox="0 0 20 20" fill="currentColor" className="h-4 w-4 shrink-0" style={{ color: "var(--theme-text-muted, #EF4444)" }}>
              <path fillRule="evenodd" d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.168 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495zM10 5a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 5zm0 9a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd" />
            </svg>
            <p className="text-xs font-medium leading-snug" style={{ color: "var(--theme-text-muted, #6B7280)" }}>
              Ce profil a été signalé comme potentiellement suspect. Soyez vigilant lors de vos transactions.
            </p>
          </div>
        )}

        <SellerHeader
          displayName={seller.displayName}
          subtitle={seller.subtitle || null}
          bio={seller.bio}
          avatarUrl={seller.avatarUrl}
          coverUrl={seller.coverUrl}
          headerStyle={(seller.headerLayout as HeaderStyle) || resolvedTheme.headerStyle}
          avatarStyle={(seller.imageStyle as "circle" | "rounded" | "square") || resolvedTheme.avatarStyle}
          socialPosition={resolvedTheme.socialPosition}
          supportsCover={resolvedTheme.supportsCover}
          showAvatar={seller.showAvatar !== false}
          socialLinks={{
            instagramUrl: seller.instagramUrl,
            tiktokUrl: seller.tiktokUrl,
            youtubeUrl: seller.youtubeUrl,
            facebookUrl: seller.facebookUrl,
            whatsappNumber: seller.whatsappNumber,
            twitterUrl: seller.twitterUrl,
            telegramUrl: seller.telegramUrl,
            snapchatUrl: seller.snapchatUrl,
            websiteUrl: seller.websiteUrl,
          }}
          isVerified={seller.kycStatus === "APPROVED"}
        />

        {/* Blocks grid: single column mobile, 2 columns desktop */}
        <div
          className="mt-5 grid grid-cols-1 items-start md:mt-10 "
          style={
            {
              gap: resolvedTheme.blockSpacing,
              "--desktop-gap": "16px",
            } as React.CSSProperties
          }
        >
          {seller.blocks.map((block) => (
            <BlockRenderer
              key={block.id}
              block={block}
              sellerSlug={seller.slug}
              sellerTimezone={seller.timezone || "Africa/Dakar"}
              sellerName={seller.displayName}
              blockLayout={resolvedTheme.blockLayout}
            />
          ))}
        </div>

        <IzyFooter
          slug={slug}
          showFooter={seller.plan !== "PRO"}
          headerStyle={(seller.headerLayout as string) || resolvedTheme.headerStyle}
          instagramUrl={seller.instagramUrl}
          tiktokUrl={seller.tiktokUrl}
          youtubeUrl={seller.youtubeUrl}
          facebookUrl={seller.facebookUrl}
          whatsappNumber={seller.whatsappNumber}
          twitterUrl={seller.twitterUrl}
          telegramUrl={seller.telegramUrl}
          snapchatUrl={seller.snapchatUrl}
          websiteUrl={seller.websiteUrl}
        />
      </div>
    </StoreThemeProvider>
  );
}
